### PR TITLE
Little updates - Update README.md, add Bug reporter, add GPL-3.0 License

### PR DESCRIPTION
**Pull request by p4535992**
- Update README.md
- add Bug reporter
- add GPL-3.0 License

I guessed the license from the warpgate dependency.

### CODE REVIEW

**Comment by theripper93** [comment]
not sure why you are adding a licence to my module lol. The fact that it uses a dependency does not mean it inherits the license

**Comment by p4535992** [comment]
I thought you just forgot, removed the license XD.
I ask you to put the license you prefer because I had used your module as a starting point for another of my [modules](https://github.com/p4535992/foundryvtt-automated-polymorpher) and I was in the process of checking the licenses.

**Comment by theripper93** [comment]
That’s why you should check the licenses before you do things, this module is all rights reserved and you may not use parts of its code.

**Comment by p4535992** [comment]
I have removed the module for license reason.

**Pull request closed without merging**
